"""Unit tests for ``scripts/check_no_nonascii_asset_names.py``.

Three-pronged coverage:

1. Live-repo gate: run the real script against this tree. Exit must be 0.
   This is what fails CI the moment someone lands a bundled asset with a
   non-ASCII filename — the thing that silently breaks macOS Developer ID
   signing with "the sealed resource directory is invalid".

2. Detection logic: build a throwaway git repo plus a throwaway tar/zip and
   assert the collector finds offenders on both paths (git listing and
   archive members) while leaving ASCII names alone.

3. Ratchet semantics: new offenders fail, baselined ones do not, and a
   baseline entry whose file is gone is a note rather than a failure (so a
   PR that legitimately deletes an asset does not go red).
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path, PurePosixPath

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = PROJECT_ROOT / "scripts" / "check_no_nonascii_asset_names.py"
BASELINE_PATH = PROJECT_ROOT / "scripts" / "nonascii_asset_baseline.txt"

# A real offender shape: truncated-transcript audio, the family that made
# this check necessary in the first place.
CJK_NAME = "七天前，我们.mp3"


def _load_script_module():
    """Import the checker as a module without ``scripts`` being a package."""
    spec = importlib.util.spec_from_file_location(
        "check_no_nonascii_asset_names", SCRIPT_PATH,
    )
    assert spec and spec.loader, f"failed to load spec for {SCRIPT_PATH}"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _init_repo(root: Path) -> None:
    """A minimal git repo — the checker asks git which files exist.

    The branch name is pinned: `git init` honours init.defaultBranch, which is
    not `main` everywhere (the Windows runner proved it), and the merge-base
    tests name their base branch explicitly.
    """
    subprocess.run(
        ["git", "-c", "init.defaultBranch=main", "init", "-q"], cwd=root, check=True
    )


# ---------------------------------------------------------------------------
# 1. Live-repo gate
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_live_repo_passes() -> None:
    """Current tree must have no non-baselined non-ASCII bundled filename."""
    # 60s: the script is I/O bound (one `git ls-files`, a couple of archive
    # listings) and normally finishes well under 5s. The cap keeps CI from
    # hanging if an archive ever turns pathological.
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH)],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        "new non-ASCII bundled asset filename(s) detected:\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


@pytest.mark.unit
def test_baseline_is_sorted_and_has_no_duplicates() -> None:
    """The baseline is regenerated by --update-baseline; keep it canonical.

    A hand-edited, out-of-order or duplicated baseline produces noisy diffs
    and makes "did this list shrink?" impossible to eyeball in review.
    """
    entries = [
        line.strip()
        for line in BASELINE_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    assert entries == sorted(entries), "baseline is not sorted"
    assert len(entries) == len(set(entries)), "baseline has duplicate entries"


# ---------------------------------------------------------------------------
# 2. Detection logic
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_collects_offender_from_git_listing(tmp_path: Path) -> None:
    """An untracked-but-not-ignored asset is caught before ``git add``."""
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")
    (assets / "plain.mp3").write_bytes(b"x")

    offenders, from_archives = module.collect_offenders(tmp_path)

    assert offenders == {f"static/audio/{CJK_NAME}"}
    assert from_archives == {}


@pytest.mark.unit
def test_non_ascii_directory_with_ascii_files_is_allowed(tmp_path: Path) -> None:
    """Only basenames matter — codesign derives the identifier from those.

    Verified against a real Developer ID certificate: a bundle containing
    ``MacOS/<cjk-dir>/plain_name.png`` seals as ``identifier "plain_name"``
    and passes ``codesign --verify --deep --strict``. Flagging such paths
    would be a failure nobody could act on.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    directory = tmp_path / "static" / "素材目录"
    directory.mkdir(parents=True)
    (directory / "plain_name.png").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)

    assert offenders == set()


@pytest.mark.unit
def test_ignores_paths_outside_bundled_roots(tmp_path: Path) -> None:
    """``tests/`` carries CJK fixture paths and never reaches the .app."""
    module = _load_script_module()
    _init_repo(tmp_path)
    outside = tmp_path / "tests" / "fixtures"
    outside.mkdir(parents=True)
    (outside / CJK_NAME).write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)

    assert offenders == set()


@pytest.mark.unit
def test_ignores_gitignored_build_output(tmp_path: Path) -> None:
    """Generated payload must not make the answer depend on build state."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / ".gitignore").write_text("static/generated/\n", encoding="utf-8")
    generated = tmp_path / "static" / "generated"
    generated.mkdir(parents=True)
    (generated / CJK_NAME).write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == set()

    # …but --include-untracked is exactly the "check what I just built" mode.
    offenders_walked, _ = module.collect_offenders(tmp_path, include_untracked=True)
    assert offenders_walked == {f"static/generated/{CJK_NAME}"}


@pytest.mark.unit
def test_collects_offender_inside_unpacked_archives(tmp_path: Path) -> None:
    """Members of assets/*.tar.gz and pngtuber-packs/*.zip count as bundled.

    Both are expanded into ``static/`` at build time, so a non-ASCII member
    reaches Contents/MacOS even though it never appears in the source tree.
    Offenders are reported at their post-unpack destination.
    """
    module = _load_script_module()
    _init_repo(tmp_path)

    payload = tmp_path / "payload.bin"
    payload.write_bytes(b"x")

    (tmp_path / "assets").mkdir()
    with tarfile.open(tmp_path / "assets" / "model.tar.gz", "w:gz") as tar:
        tar.add(payload, arcname=f"model/expressions/{CJK_NAME}")
        tar.add(payload, arcname="model/model.moc3")

    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    with zipfile.ZipFile(packs / "tuber.zip", "w") as archive:
        archive.writestr(f"layers/{CJK_NAME}", "x")
    # unpack_builtin_pngtuber.py drives off this manifest: each listed archive
    # is expanded under its own `folder`, which is where members really land.
    (packs / "manifest.json").write_text(
        json.dumps({"models": [{"folder": "tuber", "archive": "tuber.zip"}]}),
        encoding="utf-8",
    )

    offenders, from_archives = module.collect_offenders(tmp_path)

    assert offenders == {
        f"static/model/expressions/{CJK_NAME}",
        f"static/pngtuber/tuber/layers/{CJK_NAME}",
    }
    assert from_archives[f"static/model/expressions/{CJK_NAME}"] == (
        "assets/model.tar.gz"
    )
    assert from_archives[f"static/pngtuber/tuber/layers/{CJK_NAME}"] == (
        "frontend/pngtuber-packs/tuber.zip"
    )


# ---------------------------------------------------------------------------
# 3. Ratchet semantics
# ---------------------------------------------------------------------------


def _write_baseline(root: Path, entries: list[str]) -> None:
    """Seed a grandfathered baseline directly, the way a human would."""
    path = root / "scripts" / "nonascii_asset_baseline.txt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# grandfathered\n" + "".join(f"{e}\n" for e in sorted(entries)),
        encoding="utf-8",
    )


def _run_in(root: Path, module, *argv: str) -> int:
    """Run ``main`` with the module repointed at a throwaway tree."""
    module.REPO_ROOT = root
    module.BASELINE_PATH = root / "scripts" / "nonascii_asset_baseline.txt"
    return module.main(list(argv))


@pytest.mark.unit
def test_new_offender_fails_but_baselined_one_passes(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")

    # No baseline yet -> the file is new -> fail, with the codesign rationale
    # spelled out rather than a bare path.
    assert _run_in(tmp_path, module) == 1
    captured = capsys.readouterr()
    assert f"static/audio/{CJK_NAME}" in captured.out
    assert "NONASCII_ASSET_NAME" in captured.out
    assert "sealed resource directory is invalid" in captured.err

    # Grandfathering is a deliberate, hand-written act — --update-baseline
    # refuses to do it (see test_update_baseline_only_ever_shrinks).
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    assert _run_in(tmp_path, module) == 0

    # A second offender still fails even though the first is baselined.
    (assets / f"another-{CJK_NAME}").write_bytes(b"x")
    assert _run_in(tmp_path, module) == 1


@pytest.mark.unit
def test_stale_baseline_entry_is_a_note_not_a_failure(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Deleting a grandfathered asset is progress; it must not go red."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    offender = assets / CJK_NAME
    offender.write_bytes(b"x")

    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    offender.unlink()

    assert _run_in(tmp_path, module) == 0
    captured = capsys.readouterr()
    assert "--update-baseline" in captured.err
    assert f"static/audio/{CJK_NAME}" in captured.err


@pytest.mark.unit
def test_update_baseline_refuses_build_dependent_input(tmp_path: Path) -> None:
    """A baseline seeded from local build output would differ per machine."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()

    assert _run_in(tmp_path, module, "--update-baseline", "--include-untracked") == 2


@pytest.mark.unit
def test_update_baseline_only_ever_shrinks(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The documented command must not be a way to grandfather a new asset.

    Rewriting the baseline from the current tree would make `offenders -
    baseline` empty for a file added in the same PR, turning the ratchet into
    a rubber stamp.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")
    gone = f"static/audio/deleted-{CJK_NAME}"
    _write_baseline(tmp_path, [gone])

    assert _run_in(tmp_path, module, "--update-baseline") == 1
    captured = capsys.readouterr()
    assert "may only shrink" in captured.err
    assert f"static/audio/{CJK_NAME}" in captured.err

    # The vanished entry is still dropped — shrinking is the whole point —
    # but the new offender was not written, so the tree stays red.
    baseline = module.load_baseline(tmp_path / "scripts" / "nonascii_asset_baseline.txt")
    assert baseline == set()
    assert _run_in(tmp_path, module) == 1


@pytest.mark.unit
def test_baseline_growth_against_base_ref_fails(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Hand-editing the baseline is caught by the diff against the merge base.

    --update-baseline refusing to add is only half the ratchet; a contributor
    can still type the line by hand. Comparing with the base ref is what makes
    "only shrinks" actually true.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    _write_baseline(tmp_path, [])
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "base"],
        cwd=tmp_path,
        check=True,
    )

    # Add the asset AND the matching baseline line — the in-tree comparison
    # alone sees nothing wrong.
    (assets / CJK_NAME).write_bytes(b"x")
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    assert _run_in(tmp_path, module) == 0

    assert _run_in(tmp_path, module, "--base", "HEAD") == 1
    captured = capsys.readouterr()
    assert f"+ static/audio/{CJK_NAME}" in captured.err

    # Shrinking against the same base ref stays green.
    _write_baseline(tmp_path, [])
    assert _run_in(tmp_path, module, "--base", "HEAD") == 1  # asset now unbaselined
    (assets / CJK_NAME).unlink()
    assert _run_in(tmp_path, module, "--base", "HEAD") == 0


@pytest.mark.unit
def test_missing_baseline_at_base_ref_is_not_growth(tmp_path: Path) -> None:
    """First landing of this check: the base ref has no baseline to diff."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "static").mkdir()
    (tmp_path / "static" / "ok.txt").write_bytes(b"x")
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "base"],
        cwd=tmp_path,
        check=True,
    )
    _write_baseline(tmp_path, ["static/audio/whatever.mp3"])

    assert _run_in(tmp_path, module, "--base", "HEAD") == 0


@pytest.mark.unit
def test_tar_hard_link_member_counts_as_extracted(tmp_path: Path) -> None:
    """`tar -xzm` materializes hard links, so their names reach the payload.

    TarInfo.isfile() is False for a hard-link entry, which used to hide a
    non-ASCII name that the build nevertheless writes into static/.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    payload = tmp_path / "payload.bin"
    payload.write_bytes(b"x")

    (tmp_path / "assets").mkdir()
    with tarfile.open(tmp_path / "assets" / "model.tar.gz", "w:gz") as tar:
        tar.add(payload, arcname="model/real.png")
        link = tarfile.TarInfo(f"model/{CJK_NAME}")
        link.type = tarfile.LNKTYPE
        link.linkname = "model/real.png"
        tar.addfile(link)

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"static/model/{CJK_NAME}"}


@pytest.mark.unit
def test_zip_outside_the_pngtuber_manifest_is_ignored(tmp_path: Path) -> None:
    """Only manifest-listed packs are unpacked; the rest ship opaque."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    with zipfile.ZipFile(packs / "unused.zip", "w") as archive:
        archive.writestr(f"layers/{CJK_NAME}", "x")
    (packs / "manifest.json").write_text(json.dumps({"models": []}), encoding="utf-8")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == set()


@pytest.mark.unit
def test_only_the_packaged_docs_subtree_is_scanned(tmp_path: Path) -> None:
    """The build packs docs/zh-CN/guide, not docs/ — no false positives."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packaged = tmp_path / "docs" / "zh-CN" / "guide"
    packaged.mkdir(parents=True)
    (packaged / f"{CJK_NAME}.md").write_bytes(b"x")
    elsewhere = tmp_path / "docs" / "design"
    elsewhere.mkdir(parents=True)
    (elsewhere / f"{CJK_NAME}.md").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"docs/zh-CN/guide/{CJK_NAME}.md"}


@pytest.mark.unit
def test_model_manifest_filename_is_checked_without_a_build(tmp_path: Path) -> None:
    """The .onnx weights are gitignored; the name that will be written is not.

    Both manifest shapes are covered: `filename` at the top level and inside an
    `assets` list. Without this, the two model roots would only pay off under
    --include-untracked, which CI never runs.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    for rel in module.MODEL_MANIFESTS:
        (tmp_path / rel).parent.mkdir(parents=True, exist_ok=True)
    top_level, nested = module.MODEL_MANIFESTS[1], module.MODEL_MANIFESTS[0]
    (tmp_path / top_level).write_text(
        json.dumps({"filename": f"{CJK_NAME}.onnx"}), encoding="utf-8"
    )
    (tmp_path / nested).write_text(
        json.dumps({"assets": [{"filename": "ascii.onnx"}, {"filename": f"x{CJK_NAME}.onnx"}]}),
        encoding="utf-8",
    )

    offenders, from_archives = module.collect_offenders(tmp_path)

    top_dir = str(Path(top_level).parent).replace("\\", "/")
    nested_dir = str(Path(nested).parent).replace("\\", "/")
    assert offenders == {
        f"{top_dir}/{CJK_NAME}.onnx",
        f"{nested_dir}/x{CJK_NAME}.onnx",
    }
    assert from_archives[f"{top_dir}/{CJK_NAME}.onnx"] == top_level


@pytest.mark.unit
def test_malformed_manifest_is_a_loud_error(tmp_path: Path) -> None:
    """"No packs found" and "the manifest is a list" must not look the same."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    (packs / "manifest.json").write_text(json.dumps([{"folder": "x"}]), encoding="utf-8")

    with pytest.raises(SystemExit) as excinfo:
        module.collect_offenders(tmp_path)
    assert excinfo.value.code == 2

    (packs / "manifest.json").write_text(json.dumps({"models": "nope"}), encoding="utf-8")
    with pytest.raises(SystemExit) as excinfo:
        module.collect_offenders(tmp_path)
    assert excinfo.value.code == 2


@pytest.mark.unit
def test_unresolvable_base_ref_fails_instead_of_passing(tmp_path: Path) -> None:
    """A ref that cannot be resolved must not read as "the baseline didn't grow".

    Otherwise a shallow clone that never fetched origin/main turns the ratchet
    green exactly when it is supposed to bite.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    _write_baseline(tmp_path, ["static/audio/whatever.mp3"])

    # SystemExit(2), like the other environment failures in this script
    # (unreadable git listing, malformed manifest) — not a lint verdict.
    with pytest.raises(SystemExit) as excinfo:
        _run_in(tmp_path, module, "--base", "origin/nope")
    assert excinfo.value.code == 2


@pytest.mark.unit
def test_frontend_scan_covers_output_and_sources_but_not_tooling(tmp_path: Path) -> None:
    """dist/ is what ships; src/ is where the emitted names come from.

    Files outside both — configs, lockfiles, node tooling — never contribute a
    basename to the payload, so they stay out of scope.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    root = tmp_path / "frontend" / "plugin-manager"
    (root / "src").mkdir(parents=True)
    (root / "dist" / "assets").mkdir(parents=True)
    (root / "src" / f"{CJK_NAME}.vue").write_bytes(b"x")
    (root / "dist" / "assets" / f"{CJK_NAME}.js").write_bytes(b"x")
    (root / f"{CJK_NAME}.config.ts").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {
        f"frontend/plugin-manager/src/{CJK_NAME}.vue",
        f"frontend/plugin-manager/dist/assets/{CJK_NAME}.js",
    }


@pytest.mark.unit
def test_plugin_stage_filter_matches_the_real_build_rules(tmp_path: Path) -> None:
    """Pin the mirrored staging filter against the implementation it copies.

    The checker cannot import plugin.neko_plugin_cli.core.build_rules (pydantic;
    the analyze job runs on a bare interpreter), so it reimplements the file-side
    of should_skip_path. This test imports the real one and demands the same
    verdict, so the copy cannot drift unnoticed.
    """
    from plugin.neko_plugin_cli.core.build_rules import load_build_rules, should_skip_path

    module = _load_script_module()
    plugin_dir = tmp_path / "plugin" / "plugins" / "demo"
    plugin_dir.mkdir(parents=True)
    # Two rule shapes, because an `include` allow-list masks every other verdict:
    # with it present, anything unmatched is dropped regardless of why. No plugin
    # in this repo currently uses `include`, so the no-include case is the one
    # that actually runs today — and the only one where exclude-driven directory
    # pruning is observable.
    base_rules = {
        # Padded on purpose: BuildRuleSet strips entries, and a mirror that
        # does not would reject everything the allow-list should have kept.
        # "cache" matches a directory, not any file path — the real walk prunes
        # the subtree through should_skip_path(is_dir=True).
        "exclude": ["*.tmp", " secrets/* ", "cache"],
        "exclude_dirs": ["tests", "local_logs"],
        "exclude_files": ["README.md", "*.bak"],
    }
    for build_table in (base_rules, {**base_rules, "include": ["*.py", " assets/* ", "data layer/*"]}):
        _assert_stage_filter_parity(plugin_dir, build_table, module, should_skip_path, load_build_rules)


def _assert_stage_filter_parity(
    plugin_dir: Path, build_table: dict, module, should_skip_path, load_build_rules
) -> None:
    def _toml_list(values: list[str]) -> str:
        return "[" + ", ".join(f'"{value}"' for value in values) + "]"

    (plugin_dir / "pyproject.toml").write_text(
        "\n".join(
            ["[tool.neko.build]"]
            + [f"{key} = {_toml_list(value)}" for key, value in build_table.items()]
        ),
        encoding="utf-8",
    )
    rules = load_build_rules({"tool": {"neko": {"build": build_table}}})

    keep = module._plugin_stage_filter(plugin_dir.parents[2])
    relatives = [
        "runtime.py",
        "README.md",
        "notes.bak",
        "scratch.tmp",
        "store.db",
        "runtime.log",
        "cached.pyc",
        "CACHED.PYC",
        "cached.PYO",
        ".DS_Store",
        "tests/test_runtime.py",
        "tests/nested/deep.json",
        "local_logs/private.txt",
        "secrets/token.json",
        "dist/bundle.js",
        "build/out.js",
        "__pycache__/mod.pyc",
        ".github/workflows/ci.yml",
        ".vscode/settings.json",
        ".mypy_cache/module.json",
        "cache/blob.json",
        "cache/nested/blob.json",
        "data layer/worker.py",
        "assets/nested/ok.png",
        # Not matched by any `include` pattern -> dropped by the allow-list.
        "docs/manual.md",
        "styles/theme.css",
    ]
    # Demand the same verdict in both directions. One direction is a hole (the
    # mirror drops a path that really ships, so the check stops looking at it),
    # the other only a false positive — but a mismatch either way means the copy
    # has drifted, and the fix is the same one line. The sole documented
    # asymmetry is .db/.log, which staging strips afterwards rather than through
    # these rules, so should_skip_path has no opinion on them.
    def _really_staged(relative: str) -> bool:
        """Model _copy_plugin_tree: prune directories first, then judge the file."""
        parts = PurePosixPath(relative).parts
        for index in range(len(parts) - 1):
            ancestor = Path(*parts[: index + 1])
            if should_skip_path(ancestor, is_dir=True, rules=rules):
                return False
        return not should_skip_path(Path(relative), is_dir=False, rules=rules)

    for relative in relatives:
        mirrored_keep = keep(f"plugin/plugins/demo/{relative}")
        if PurePosixPath(relative).suffix.lower() in {".db", ".log"}:
            assert not mirrored_keep, relative
            continue
        real_keeps = _really_staged(relative)
        assert mirrored_keep == real_keeps, (
            f"mirror and build rules disagree on {relative}: "
            f"mirror keeps={mirrored_keep}, staging keeps={real_keeps}"
        )

    # And it must actually drop the families it exists for.
    for dropped in (
        "tests/test_runtime.py",
        "local_logs/private.txt",
        "secrets/token.json",
        "scratch.tmp",
        "README.md",
        "notes.bak",
        "dist/bundle.js",
        "__pycache__/mod.pyc",
        ".mypy_cache/module.json",
        "cache/blob.json",
        "store.db",
        "runtime.log",
        # NOT docs/manual.md: without an `include` allow-list it is staged, and
        # the parity loop above already pins both rule shapes.
    ):
        assert not keep(f"plugin/plugins/demo/{dropped}"), dropped


@pytest.mark.unit
def test_excluded_plugin_paths_are_not_reported(tmp_path: Path) -> None:
    """A CJK name under a path the stage drops must not fail the build."""
    module = _load_script_module()
    _init_repo(tmp_path)
    plugin_dir = tmp_path / "plugin" / "plugins" / "demo"
    (plugin_dir / "tests").mkdir(parents=True)
    (plugin_dir / "pyproject.toml").write_text(
        '[tool.neko.build]\nexclude_dirs = ["tests"]\n', encoding="utf-8"
    )
    (plugin_dir / "tests" / f"{CJK_NAME}.json").write_bytes(b"x")
    (plugin_dir / f"{CJK_NAME}.db").write_bytes(b"x")
    (plugin_dir / "__pycache__").mkdir()
    (plugin_dir / "__pycache__" / f"{CJK_NAME}.pyc").write_bytes(b"x")
    shipped = plugin_dir / "assets"
    shipped.mkdir()
    (shipped / f"{CJK_NAME}.png").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"plugin/plugins/demo/assets/{CJK_NAME}.png"}


@pytest.mark.unit
def test_windows_zip_separators_are_normalized(tmp_path: Path) -> None:
    """A CJK directory holding an ASCII basename is allowed; only the name counts.

    The fixture writes that member with a Windows backslash separator, which is
    what used to make the whole string read as a single non-ASCII basename.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    with zipfile.ZipFile(packs / "tuber.zip", "w") as archive:
        archive.writestr("中文目录\\plain.png", "x")
        archive.writestr(f"层\\{CJK_NAME}", "x")
    (packs / "manifest.json").write_text(
        json.dumps({"models": [{"folder": "tuber", "archive": "tuber.zip"}]}),
        encoding="utf-8",
    )

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"static/pngtuber/tuber/层/{CJK_NAME}"}


@pytest.mark.unit
def test_vite_public_assets_are_scanned(tmp_path: Path) -> None:
    """public/ is copied verbatim into gitignored output, so scan the source."""
    module = _load_script_module()
    _init_repo(tmp_path)
    for rel in ("frontend/plugin-manager/public", "frontend/react-neko-chat/public"):
        (tmp_path / rel).mkdir(parents=True)
        (tmp_path / rel / f"{CJK_NAME}.png").write_bytes(b"x")
    (tmp_path / "frontend" / "react-neko-chat" / f"{CJK_NAME}.config.ts").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {
        f"frontend/plugin-manager/public/{CJK_NAME}.png",
        f"frontend/react-neko-chat/public/{CJK_NAME}.png",
    }


@pytest.mark.unit
def test_only_packaged_config_and_data_entries_are_scanned(tmp_path: Path) -> None:
    """config/ and data/ ship a named subset, not the whole root."""
    module = _load_script_module()
    _init_repo(tmp_path)
    for rel in (
        f"config/characters/{CJK_NAME}.json",
        f"config/changelog/{CJK_NAME}.md",
        f"data/browser_use_prompts/{CJK_NAME}.md",
        f"config/prompts/{CJK_NAME}.md",
        f"data/notes/{CJK_NAME}.md",
    ):
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {
        f"config/characters/{CJK_NAME}.json",
        f"config/changelog/{CJK_NAME}.md",
        f"data/browser_use_prompts/{CJK_NAME}.md",
    }


@pytest.mark.unit
def test_uppercase_bytecode_suffix_is_still_scanned(tmp_path: Path) -> None:
    """The build rules compare suffixes case-sensitively, so `.PYC` ships.

    Folding case in the mirrored filter would drop such a file from the scan
    while staging still installs it — the one drift direction that hides a
    signing break rather than merely adding noise.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    plugin_dir = tmp_path / "plugin" / "plugins" / "demo"
    plugin_dir.mkdir(parents=True)
    (plugin_dir / f"{CJK_NAME}.PYC").write_bytes(b"x")
    (plugin_dir / f"{CJK_NAME}.pyc").write_bytes(b"x")
    # .db/.log are stripped case-insensitively after staging, so both go.
    (plugin_dir / f"{CJK_NAME}.DB").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"plugin/plugins/demo/{CJK_NAME}.PYC"}


@pytest.mark.unit
def test_vite_source_basenames_are_scanned_anywhere_under_src(tmp_path: Path) -> None:
    """Vite emits by import, not by directory, so the whole source tree counts.

    An imported asset above the inline limit keeps its basename wherever it
    lives, and a dynamically imported module donates its basename to the chunk
    name. Both outputs are gitignored, so the source tree is the only place a
    plain CI run can see these names.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    for rel in ("src/assets", "src/components", "src/views"):
        (tmp_path / "frontend" / "plugin-manager" / rel).mkdir(parents=True)
    root = tmp_path / "frontend" / "plugin-manager"
    (root / "src" / "assets" / f"{CJK_NAME}.png").write_bytes(b"x")
    (root / "src" / "components" / f"{CJK_NAME}.png").write_bytes(b"x")
    (root / "src" / "views" / f"{CJK_NAME}.vue").write_bytes(b"x")
    # Outside any source tree: build tooling, never emitted with its own name.
    (root / f"{CJK_NAME}.config.ts").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {
        f"frontend/plugin-manager/src/assets/{CJK_NAME}.png",
        f"frontend/plugin-manager/src/components/{CJK_NAME}.png",
        f"frontend/plugin-manager/src/views/{CJK_NAME}.vue",
    }


@pytest.mark.unit
def test_include_allow_list_keeps_unpackaged_files_out_of_the_scan(tmp_path: Path) -> None:
    """With `include` set, staging drops everything unmatched — so do not report it."""
    module = _load_script_module()
    _init_repo(tmp_path)
    plugin_dir = tmp_path / "plugin" / "plugins" / "demo"
    (plugin_dir / "assets").mkdir(parents=True)
    (plugin_dir / "docs").mkdir()
    (plugin_dir / "pyproject.toml").write_text(
        '[tool.neko.build]\ninclude = ["assets/*"]\n', encoding="utf-8"
    )
    (plugin_dir / "assets" / f"{CJK_NAME}.png").write_bytes(b"x")
    (plugin_dir / "docs" / f"{CJK_NAME}.md").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"plugin/plugins/demo/assets/{CJK_NAME}.png"}


@pytest.mark.unit
def test_baseline_growth_is_measured_at_the_merge_base(tmp_path: Path) -> None:
    """A cleanup landing on main after the branch was cut must not read as growth.

    Comparing against the tip would show entries the branch never added — they
    were present when it was created and only removed on main afterwards.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    commit = ["-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm"]
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(["git", *commit, "shared base"], cwd=tmp_path, check=True)
    subprocess.run(["git", "branch", "feature"], cwd=tmp_path, check=True)

    # main removes the grandfathered asset and its baseline line.
    (assets / CJK_NAME).unlink()
    _write_baseline(tmp_path, [])
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(["git", *commit, "main: shrink baseline"], cwd=tmp_path, check=True)

    # The feature branch still carries the entry it inherited.
    subprocess.run(["git", "checkout", "-q", "feature"], cwd=tmp_path, check=True)
    module.REPO_ROOT = tmp_path
    module.BASELINE_PATH = tmp_path / "scripts" / "nonascii_asset_baseline.txt"
    assert module._baseline_growth(tmp_path, "main") == []

    # …while a line this branch really adds is still caught.
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}", "static/audio/new.mp3"])
    assert module._baseline_growth(tmp_path, "main") == ["static/audio/new.mp3"]


@pytest.mark.unit
def test_missing_merge_base_fails_instead_of_using_the_tip(tmp_path: Path) -> None:
    """Unrelated histories must not silently degrade to a tip comparison.

    That fallback would restore the very bug the merge-base lookup fixes, and
    it would do it invisibly — the same failure shape as an unresolvable ref.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    commit = ["-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm"]
    _write_baseline(tmp_path, ["static/audio/base.mp3"])
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(["git", *commit, "main"], cwd=tmp_path, check=True)

    # An orphan branch shares no history with main.
    subprocess.run(["git", "checkout", "-q", "--orphan", "unrelated"], cwd=tmp_path, check=True)
    _write_baseline(tmp_path, ["static/audio/other.mp3"])
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(["git", *commit, "unrelated"], cwd=tmp_path, check=True)

    module.REPO_ROOT = tmp_path
    module.BASELINE_PATH = tmp_path / "scripts" / "nonascii_asset_baseline.txt"
    with pytest.raises(SystemExit) as excinfo:
        module._baseline_growth(tmp_path, "main")
    assert excinfo.value.code == 2


@pytest.mark.unit
def test_loose_plugin_runtime_artifacts_are_not_reported(tmp_path: Path) -> None:
    """`.db`/`.log` directly under plugin/plugins/ are swept after staging too.

    _remove_private_runtime_artifacts walks the whole stage, including the loose
    files copied from the plugins root, so reporting one is a false failure.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    loose = tmp_path / "plugin" / "plugins"
    loose.mkdir(parents=True)
    (loose / f"{CJK_NAME}.db").write_bytes(b"x")
    (loose / f"{CJK_NAME}.LOG").write_bytes(b"x")
    (loose / f"{CJK_NAME}.json").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"plugin/plugins/{CJK_NAME}.json"}


@pytest.mark.unit
def test_steamworks_native_libraries_are_scanned(tmp_path: Path) -> None:
    """--include-package=steamworks carries this directory in as package data."""
    module = _load_script_module()
    _init_repo(tmp_path)
    steamworks = tmp_path / "steamworks"
    steamworks.mkdir()
    (steamworks / f"{CJK_NAME}.dylib").write_bytes(b"x")
    (steamworks / "SteamworksPy.dylib").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"steamworks/{CJK_NAME}.dylib"}
