"""Generate plugin scaffolding files from collected options."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from plugin._types.plugin_types import (
    SCAFFOLDABLE_PLUGIN_TYPES,
    format_unsupported_scaffold_type,
)

_PYTHON_PLUGIN_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_MARKET_REPO_PREFIX = "n.e.k.o_plugin_"
_DEFAULT_NEKO_REPOSITORY = "Project-N-E-K-O/N.E.K.O"
_PLUGIN_RUFF_VERSION = "0.12.4"
MARKET_ACTIONS_MANAGED_HEADER = (
    "# Generated by neko-plugin\n"
    "# managed-template: plugin-market-actions-v1\n"
)


@dataclass
class PluginSpec:
    """All the information needed to generate a plugin scaffold."""

    plugin_id: str
    name: str = ""
    plugin_type: str = "plugin"
    description: str = ""
    version: str = "0.1.0"
    author_name: str = ""
    author_email: str = ""
    entry_point_override: str = ""

    # Features
    features: list[str] = field(default_factory=list)
    # Possible features:
    #   lifecycle, entry_point, timer, message, store, cross_plugin,
    #   static_ui, async_support, bus_events, settings

    create_pyproject: bool = True
    create_readme: bool = True
    create_tests: bool = True
    create_gitignore: bool = True
    create_vscode: bool = True
    create_github_actions: bool = False
    neko_repository: str = _DEFAULT_NEKO_REPOSITORY
    neko_ref: str = "main"
    quick_start: bool = False

    @property
    def class_name(self) -> str:
        # Split on both _ and - for CamelCase conversion
        parts = re.split(r"[_-]", self.plugin_id)
        return "".join(p.capitalize() for p in parts if p) + "Plugin"

    @property
    def entry_point(self) -> str:
        if self.entry_point_override:
            return self.entry_point_override
        return f"plugin.plugins.{self.plugin_id}:{self.class_name}"

    @property
    def module_path(self) -> str:
        return f"plugin.plugins.{self.plugin_id}"


def generate_plugin(spec: PluginSpec, target_dir: Path) -> list[Path]:
    """Generate all scaffold files and return the list of created paths."""
    if spec.plugin_type not in SCAFFOLDABLE_PLUGIN_TYPES:
        raise ValueError(format_unsupported_scaffold_type(spec.plugin_type))
    if not _PYTHON_PLUGIN_ID_RE.fullmatch(spec.plugin_id):
        raise ValueError(
            "plugin_id must be a valid Python package name: use letters, numbers, and underscores only"
        )
    target_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []

    # plugin.toml
    toml_path = target_dir / "plugin.toml"
    toml_path.write_text(_render_plugin_toml(spec), encoding="utf-8", newline="\n")
    created.append(toml_path)

    # config.example.toml
    config_example_path = target_dir / "config.example.toml"
    config_example_path.write_text(
        _render_config_example_toml(spec),
        encoding="utf-8",
        newline="\n",
    )
    created.append(config_example_path)

    # __init__.py
    init_path = target_dir / "__init__.py"
    init_path.write_text(_render_init_py(spec), encoding="utf-8", newline="\n")
    created.append(init_path)

    # pyproject.toml (optional)
    if spec.create_pyproject:
        pyproject_path = target_dir / "pyproject.toml"
        pyproject_path.write_text(_render_pyproject_toml(spec), encoding="utf-8", newline="\n")
        created.append(pyproject_path)

    if spec.create_readme:
        readme_path = target_dir / "README.md"
        readme_path.write_text(_render_readme_md(spec), encoding="utf-8", newline="\n")
        created.append(readme_path)

    if spec.create_tests:
        tests_dir = target_dir / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)
        smoke_path = tests_dir / "test_smoke.py"
        smoke_path.write_text(_render_smoke_test(spec), encoding="utf-8", newline="\n")
        created.append(smoke_path)

    if spec.create_gitignore:
        gitignore_path = target_dir / ".gitignore"
        gitignore_path.write_text(_render_gitignore(), encoding="utf-8", newline="\n")
        created.append(gitignore_path)

    if spec.create_vscode:
        vscode_dir = target_dir / ".vscode"
        vscode_dir.mkdir(parents=True, exist_ok=True)
        settings_path = vscode_dir / "settings.json"
        settings_path.write_text(_render_vscode_settings(), encoding="utf-8", newline="\n")
        created.append(settings_path)

        tasks_path = vscode_dir / "tasks.json"
        tasks_path.write_text(_render_vscode_tasks(spec), encoding="utf-8", newline="\n")
        created.append(tasks_path)

    if spec.create_github_actions:
        ruff_config_path = target_dir / "ruff.toml"
        ruff_config_path.write_text(render_ruff_config(), encoding="utf-8", newline="\n")
        created.append(ruff_config_path)

        workflow_dir = target_dir / ".github" / "workflows"
        workflow_dir.mkdir(parents=True, exist_ok=True)
        workflow_path = workflow_dir / "verify.yml"
        workflow_path.write_text(render_verify_workflow(spec), encoding="utf-8", newline="\n")
        created.append(workflow_path)
        release_workflow_path = workflow_dir / "release.yml"
        release_workflow_path.write_text(render_release_workflow(spec), encoding="utf-8", newline="\n")
        created.append(release_workflow_path)

    return created


def generate_repo_support_files(
    spec: PluginSpec,
    target_dir: Path,
    *,
    overwrite: bool = False,
) -> list[Path]:
    """Generate repository support files for an existing plugin directory."""
    if not target_dir.is_dir():
        raise FileNotFoundError(f"plugin directory not found: {target_dir}")

    created: list[Path] = []

    if spec.create_readme:
        _write_support_file(
            target_dir / "README.md",
            _render_readme_md(spec),
            created=created,
            overwrite=overwrite,
        )

    if spec.create_tests:
        tests_dir = target_dir / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)
        _write_support_file(
            tests_dir / "test_smoke.py",
            _render_smoke_test(spec),
            created=created,
            overwrite=overwrite,
        )

    if spec.create_gitignore:
        _write_support_file(
            target_dir / ".gitignore",
            _render_gitignore(),
            created=created,
            overwrite=overwrite,
        )

    if spec.create_vscode:
        vscode_dir = target_dir / ".vscode"
        vscode_dir.mkdir(parents=True, exist_ok=True)
        _write_support_file(
            vscode_dir / "settings.json",
            _render_vscode_settings(),
            created=created,
            overwrite=overwrite,
        )
        _write_support_file(
            vscode_dir / "tasks.json",
            _render_vscode_tasks(spec),
            created=created,
            overwrite=overwrite,
        )

    if spec.create_github_actions:
        _write_support_file(
            target_dir / "ruff.toml",
            render_ruff_config(),
            created=created,
            overwrite=overwrite,
        )

        workflow_dir = target_dir / ".github" / "workflows"
        workflow_dir.mkdir(parents=True, exist_ok=True)
        _write_support_file(
            workflow_dir / "verify.yml",
            render_verify_workflow(spec),
            created=created,
            overwrite=overwrite,
        )
        _write_support_file(
            workflow_dir / "release.yml",
            render_release_workflow(spec),
            created=created,
            overwrite=overwrite,
        )

    return created


# ---------------------------------------------------------------------------
# plugin.toml
# ---------------------------------------------------------------------------

def _render_plugin_toml(spec: PluginSpec) -> str:
    lines = [
        "[plugin]",
        f'id = "{spec.plugin_id}"',
        f'name = "{_escape(spec.name or spec.plugin_id)}"',
    ]

    if spec.description:
        lines.append(f'description = "{_escape(spec.description)}"')

    lines.append(f'version = "{spec.version}"')
    lines.append(f'type = "{spec.plugin_type}"')
    lines.append(f'entry = "{spec.entry_point}"')

    if spec.author_name or spec.author_email:
        lines.append("")
        lines.append("[plugin.author]")
        if spec.author_name:
            lines.append(f'name = "{_escape(spec.author_name)}"')
        if spec.author_email:
            lines.append(f'email = "{_escape(spec.author_email)}"')

    lines.extend([
        "",
        "[plugin.sdk]",
        'recommended = ">=0.1.0,<0.2.0"',
        'supported = ">=0.1.0,<0.3.0"',
    ])

    if "store" in spec.features:
        lines.extend(["", "[plugin.store]", "enabled = true"])

    lines.append("")
    return "\n".join(lines)


def _render_config_example_toml(spec: PluginSpec) -> str:
    auto_start = "true" if "timer" in spec.features or "message" in spec.features else "false"
    return "\n".join(
        [
            "[plugin_runtime]",
            "enabled = true",
            f"auto_start = {auto_start}",
            "",
        ]
    )


# ---------------------------------------------------------------------------
# __init__.py
# ---------------------------------------------------------------------------

def _render_init_py(spec: PluginSpec) -> str:
    if spec.plugin_type == "adapter":
        return _render_adapter_init(spec)
    if spec.quick_start:
        return _render_quick_start_init(spec)
    return _render_plugin_init(spec)


def _render_quick_start_init(spec: PluginSpec) -> str:
    return f'''from typing import Any

from plugin.sdk.plugin import (
    NekoPluginBase,
    Ok,
    lifecycle,
    neko_plugin,
    plugin_entry,
)


@neko_plugin
class {spec.class_name}(NekoPluginBase):
    """{_escape(spec.name or spec.plugin_id)}"""

    def __init__(self, ctx: Any):
        super().__init__(ctx)
        self.logger = ctx.logger

    @lifecycle(id="startup")
    def on_startup(self, **_):
        self.logger.info("{spec.class_name} started")
        return Ok({{"status": "ready"}})

    @lifecycle(id="shutdown")
    def on_shutdown(self, **_):
        self.logger.info("{spec.class_name} stopped")
        return Ok({{"status": "stopped"}})

    @plugin_entry(
        id="hello",
        name="Hello",
        description="Say hello",
        input_schema={{
            "type": "object",
            "properties": {{
                "name": {{"type": "string", "default": "World"}}
            }}
        }}
    )
    async def hello(self, name: str = "World", **_):
        return Ok({{"message": f"Hello, {{name}}!"}})
'''


def _render_plugin_init(spec: PluginSpec) -> str:
    imports = ["NekoPluginBase", "neko_plugin", "Ok"]

    if "lifecycle" in spec.features or "entry_point" in spec.features:
        # Always include these for non-quick-start plugins
        pass
    if "lifecycle" in spec.features:
        imports.append("lifecycle")
    if "entry_point" in spec.features:
        imports.append("plugin_entry")
    if "timer" in spec.features:
        imports.append("timer_interval")
    if "message" in spec.features:
        imports.append("message")
    if "store" in spec.features:
        imports.append("PluginStore")
    if "settings" in spec.features:
        imports.append("PluginSettings")

    is_async = "async_support" in spec.features

    lines = [
        "from typing import Any",
        "",
        "from plugin.sdk.plugin import (",
        *(f"    {name}," for name in sorted(imports)),
        ")",
    ]

    lines.extend([
        "",
        "",
        "@neko_plugin",
        f"class {spec.class_name}(NekoPluginBase):",
        f'    """{_escape(spec.name or spec.plugin_id)}"""',
    ])

    if "settings" in spec.features:
        lines.extend([
            "",
            "    class Settings(PluginSettings):",
            "        pass",
        ])

    lines.extend([
        "",
        "    def __init__(self, ctx: Any):",
        "        super().__init__(ctx)",
        "        self.logger = ctx.logger",
    ])

    if "store" in spec.features:
        lines.append("        self.store = PluginStore(ctx)")

    # lifecycle
    if "lifecycle" in spec.features:
        if is_async:
            lines.extend([
                "",
                '    @lifecycle(id="startup")',
                "    async def on_startup(self, **_):",
                f'        self.logger.info("{spec.class_name} started")',
                '        return Ok({"status": "ready"})',
                "",
                '    @lifecycle(id="shutdown")',
                "    async def on_shutdown(self, **_):",
                f'        self.logger.info("{spec.class_name} stopped")',
                '        return Ok({"status": "stopped"})',
            ])
        else:
            lines.extend([
                "",
                '    @lifecycle(id="startup")',
                "    def on_startup(self, **_):",
                f'        self.logger.info("{spec.class_name} started")',
                '        return Ok({"status": "ready"})',
                "",
                '    @lifecycle(id="shutdown")',
                "    def on_shutdown(self, **_):",
                f'        self.logger.info("{spec.class_name} stopped")',
                '        return Ok({"status": "stopped"})',
            ])

    # entry point
    if "entry_point" in spec.features:
        lines.extend([
            "",
            "    @plugin_entry(",
            '        id="example",',
            '        name="Example Entry",',
            '        description="An example entry point",',
            "        input_schema={",
            '            "type": "object",',
            '            "properties": {',
            '                "input": {"type": "string", "default": ""}',
            "            }",
            "        }",
            "    )",
            "    async def example(self, input: str = \"\", **_):",
            '        return Ok({"result": input})',
        ])

    # timer
    if "timer" in spec.features:
        lines.extend([
            "",
            '    @timer_interval(id="heartbeat", seconds=60, auto_start=True)',
            "    def heartbeat(self, **_):",
            '        self.logger.debug("heartbeat")',
            '        return Ok({"alive": True})',
        ])

    # message
    if "message" in spec.features:
        async_kw = "async " if is_async else ""
        lines.extend([
            "",
            '    @message(id="handle_message", auto_start=True)',
            f"    {async_kw}def handle_message(self, text: str = \"\", **_):",
            '        self.logger.info(f"Received: {text}")',
            '        return Ok({"handled": True})',
        ])

    lines.append("")
    return "\n".join(lines)


def _render_adapter_init(spec: PluginSpec) -> str:
    return f'''from typing import Any

from plugin.sdk.adapter import NekoAdapterPlugin
from plugin.sdk.plugin import Ok, lifecycle, neko_plugin, plugin_entry


@neko_plugin
class {spec.class_name}(NekoAdapterPlugin):
    """{_escape(spec.name or spec.plugin_id)}"""

    def __init__(self, ctx: Any):
        super().__init__(ctx)
        self.logger = ctx.logger

    @lifecycle(id="startup")
    async def on_startup(self, **_):
        self.logger.info("{spec.class_name} started")
        return Ok({{"status": "ready"}})

    @lifecycle(id="shutdown")
    async def on_shutdown(self, **_):
        self.logger.info("{spec.class_name} stopped")
        return Ok({{"status": "stopped"}})

    @plugin_entry(id="handle_request")
    async def handle_request(self, raw_data: dict = None, **_):
        return Ok({{"received": raw_data}})
'''


# ---------------------------------------------------------------------------
# pyproject.toml
# ---------------------------------------------------------------------------

def _render_pyproject_toml(spec: PluginSpec) -> str:
    return f'''[project]
name = "{spec.plugin_id}"
version = "{spec.version}"
dependencies = []
'''


# ---------------------------------------------------------------------------
# Repository support files
# ---------------------------------------------------------------------------

def _dependency_sync_command(plugin: str) -> str:
    return (
        "uv run --with pip python -m plugin.neko_plugin_cli.cli "
        f"sync {plugin} --clean"
    )


def _render_readme_md(spec: PluginSpec) -> str:
    name = spec.name or spec.plugin_id
    description = spec.description or "Describe what this plugin does and how to configure it."
    sync_command = _dependency_sync_command(spec.plugin_id)
    ruff_instructions = ""
    if spec.create_github_actions:
        ruff_instructions = f'''From this plugin repository root:

```bash
uvx ruff=={_PLUGIN_RUFF_VERSION} check --ignore-noqa --config ruff.toml .
```

'''
    return f'''# {name}

{description}

## Development

This repository is meant to live at:

```text
N.E.K.O/plugin/plugins/{spec.plugin_id}
```

When publishing to the plugin market, use this GitHub repository name:

```text
{_market_repo_name(spec.plugin_id)}
```

{ruff_instructions}From the N.E.K.O repository root:

```bash
{sync_command}
uv run python -m plugin.neko_plugin_cli.cli check {spec.plugin_id}
uv run python -m plugin.neko_plugin_cli.cli check -r {spec.plugin_id}
```

Python runtime dependencies are declared in `pyproject.toml` and synced into
`vendor/` for packaging. The generated `vendor/` directory is not committed;
local builds and CI recreate it before release checks.

## Market release

Push a tag matching `plugin.toml` version to create a GitHub Release asset:

```bash
git tag v{spec.version}
git push origin v{spec.version}
```

The generated `.github/workflows/release.yml` uploads `{spec.plugin_id}.neko-plugin`.
Use that GitHub Release URL when publishing a version in the plugin market.

## Entry

```toml
entry = "{spec.entry_point}"
```
'''


def _render_smoke_test(spec: PluginSpec) -> str:
    return f'''from pathlib import Path


def test_plugin_manifest_exists() -> None:
    root = Path(__file__).resolve().parents[1]
    manifest = root / "plugin.toml"
    assert manifest.is_file()
    text = manifest.read_text(encoding="utf-8")
    assert 'id = "{spec.plugin_id}"' in text
    assert 'entry = "{spec.entry_point}"' in text
'''


def _render_gitignore() -> str:
    return '''__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/
.venv/
venv/
vendor/
dist/
build/
*.egg-info/
store.db
.env
.DS_Store
'''


def _render_vscode_settings() -> str:
    return '''{
  "nekoPlugin.repoRoot": "../../..",
  "python.analysis.extraPaths": [
    "${workspaceFolder}/../../.."
  ]
}
'''


def _render_vscode_tasks(spec: PluginSpec) -> str:
    sync_command = _dependency_sync_command(spec.plugin_id)
    return f'''{{
  "version": "2.0.0",
  "tasks": [
    {{
      "label": "N.E.K.O: check {spec.plugin_id}",
      "type": "shell",
      "command": "uv run python -m plugin.neko_plugin_cli.cli check {spec.plugin_id}",
      "options": {{
        "cwd": "${{config:nekoPlugin.repoRoot}}"
      }},
      "problemMatcher": []
    }},
    {{
      "label": "N.E.K.O: sync {spec.plugin_id}",
      "type": "shell",
      "command": "{sync_command}",
      "options": {{
        "cwd": "${{config:nekoPlugin.repoRoot}}"
      }},
      "problemMatcher": []
    }},
    {{
      "label": "N.E.K.O: check -r {spec.plugin_id}",
      "type": "shell",
      "command": "uv run python -m plugin.neko_plugin_cli.cli check -r {spec.plugin_id}",
      "options": {{
        "cwd": "${{config:nekoPlugin.repoRoot}}"
      }},
      "problemMatcher": []
    }},
    {{
      "label": "N.E.K.O: build {spec.plugin_id}",
      "type": "shell",
      "command": "uv run python -m plugin.neko_plugin_cli.cli build {spec.plugin_id}",
      "options": {{
        "cwd": "${{config:nekoPlugin.repoRoot}}"
      }},
      "problemMatcher": []
    }}
  ]
}}
'''


def render_verify_workflow(spec: PluginSpec) -> str:
    return MARKET_ACTIONS_MANAGED_HEADER + f'''name: Verify N.E.K.O Plugin

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: {spec.neko_repository}/.github/workflows/plugin-market-verify.yml@{spec.neko_ref}
    with:
      plugin-id: {spec.plugin_id}
      neko-repository: {spec.neko_repository}
      neko-ref: {spec.neko_ref}
'''


def render_release_workflow(spec: PluginSpec) -> str:
    return MARKET_ACTIONS_MANAGED_HEADER + f'''name: Release N.E.K.O Plugin

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: {spec.neko_repository}/.github/workflows/plugin-market-release.yml@{spec.neko_ref}
    with:
      plugin-id: {spec.plugin_id}
      neko-repository: {spec.neko_repository}
      neko-ref: {spec.neko_ref}
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def render_ruff_config() -> str:
    """Render the blocking Ruff policy for first-party plugin source."""
    return MARKET_ACTIONS_MANAGED_HEADER + '''target-version = "py311"
line-length = 120
extend-exclude = ["vendor"]
respect-gitignore = false

[lint]
select = ["E4", "E7", "E9", "F", "I"]
'''


def _escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def _market_repo_name(plugin_id: str) -> str:
    return f"{_MARKET_REPO_PREFIX}{plugin_id}"


def _write_support_file(path: Path, content: str, *, created: list[Path], overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.write_text(content, encoding="utf-8", newline="\n")
    created.append(path)
